Description: Create a demo launch template

Parameters:
  keyId:
    Type: String
  instanceType:
    Type: String
    Default: t3.small
    AllowedValues:
      - t3.small
      - t3.medium
      - t3.large
  environment:
    Type: String
    Default: development
    AllowedValues:
      - development
      - production
  vpcId:
    Type: String

Mappings:
  amiMap:
    ca-central-1:
      amiId: ami-041a9937e9118f3f3
    us-east-1:
      amiId: ami-090fa75af13c156b4

Resources:
  instanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: IAM role used for our Launch template demo session
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore